# Nixpacks Configuration for Autonomous Task Agent
[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "python app.py"